steps:
  # build the container image
  #docker build -t asia.gcr.io/testkubenetes-370014/myapp:latest . --platform linux/amd64
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "asia.gcr.io/testkubenetes-370014/myapp:latest", "."]
  # push container image
  # docker push asia.gcr.io/testkubenetes-370014/myapp
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "asia.gcr.io/testkubenetes-370014/myapp:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/kubectl"
  args: ["apply", "-f", "deployment/dev/deployment.yml"]
  env:
  - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster2'